//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportViewerMvcWebApplication.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportViewerMvcWebApplication.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}; {1}; {2};.
        /// </summary>
        public static string ChairpersonEntry {
            get {
                return ResourceManager.GetString("ChairpersonEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairpersons:.
        /// </summary>
        public static string Chairpersons {
            get {
                return ResourceManager.GetString("Chairpersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of equipment.
        /// </summary>
        public static string ConferenceEquipmentViewTitle {
            get {
                return ResourceManager.GetString("ConferenceEquipmentViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of participants.
        /// </summary>
        public static string ConferenceParticipantsViewTitle {
            get {
                return ResourceManager.GetString("ConferenceParticipantsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferences.
        /// </summary>
        public static string Conferences {
            get {
                return ResourceManager.GetString("Conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Schedule.
        /// </summary>
        public static string ConferenceScheduleViewTitle {
            get {
                return ResourceManager.GetString("ConferenceScheduleViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditConference.
        /// </summary>
        public static string EditConference {
            get {
                return ResourceManager.GetString("EditConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needed equipment for the conference «{0}»:.
        /// </summary>
        public static string NeededEquipment {
            get {
                return ResourceManager.GetString("NeededEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not valid.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Room: {0}; Time: {1} - {2};.
        /// </summary>
        public static string RoomEntry {
            get {
                return ResourceManager.GetString("RoomEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for conference: «{0}».
        /// </summary>
        public static string ScheduleForConference {
            get {
                return ResourceManager.GetString("ScheduleForConference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section: {0}; Chairperson: {1}; Room: {2};.
        /// </summary>
        public static string SectionEntry {
            get {
                return ResourceManager.GetString("SectionEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}; {1}; {2};.
        /// </summary>
        public static string SpeakerEntry {
            get {
                return ResourceManager.GetString("SpeakerEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers:.
        /// </summary>
        public static string Speakers {
            get {
                return ResourceManager.GetString("Speakers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Talk: {0}; {1}; {2} - {3};.
        /// </summary>
        public static string TalkEntry {
            get {
                return ResourceManager.GetString("TalkEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAdded.
        /// </summary>
        public static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valid.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t select weekends.
        /// </summary>
        public static string WeeekendSelectedError {
            get {
                return ResourceManager.GetString("WeeekendSelectedError", resourceCulture);
            }
        }
    }
}
